name: Render Profile

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:

# only allows one pipeline to run for this file
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  RenderProfile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate Context
        id: context-contributions
        shell: bash
        run: |
          contributions=$(./get-contributions.sh $GITHUB_REPOSITORY_OWNER)
          # echo output into step called contributions
          echo "contributions=$contributions" >> $GITHUB_OUTPUT

      - uses: badsyntax/github-action-render-template@v0.0.1
        name: Render Template
        id: render-template
        with:
          template: README.tmpl.md
          inputs: |
            {
              "contributions": ${{ steps.context-contributions.outputs.contributions }}
            }

      - name: Write to file
        shell: bash
        run: |
          echo "${{ steps.render-template.outputs.rendered }}" > README.md
